/*
 * Copyright 2020 Alberto Enrique Alonso De la Hoz.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package View;

import Model.Mecanizado;
import Model.Util;
import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Alberto Enrique Alonso De la Hoz
 * @author Cristian Eduardo Coronado Santiago
 */
public final class FormInfo extends javax.swing.JFrame {

    public Mecanizado obj = new Mecanizado();
    public int meca = 0;
    public int material = 0;
    

    public FormInfo() {
        initComponents();
        //FormInfo.this.setLocationRelativeTo(FormInfo.this);
        FormInfo.this.setResizable(false);
        FormInfo.this.getContentPane().setBackground(Color.WHITE);
        FormInfo.this.setTitle("Resultados de mejora de rugosidad,presición y tolerancia");
        FormInfo.this.jLabelTolerancia.setVisible(false);
        FormInfo.this.jTextFieldTolerancia.setVisible(false);
    }

    public void mostrarResultados(double mecanizado,
            double tipo, Mecanizado abs) {
        obj = abs;
        meca = (int) mecanizado;
        material = (int) tipo;
        System.out.println("mecanizado: " +meca +"\n"+
        "material: "+material);
    }
    
    public void limpiar(){
        jTextFieldTolerancia.setText("");
        jTextFieldTipoDeMaterial.setText("");
        jTextFieldRugosidadFinal.setText("");
        jTextFieldPorcentajeRugosidad.setText("");
        jTextFieldPorcentajePrecision.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPorcentajeRugosidad = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPorcentajePrecision = new javax.swing.JTextField();
        jLabelMecanizado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTipoDeMaterial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldRugosidadFinal = new javax.swing.JTextField();
        jLabelTolerancia = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldTolerancia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setText("RESULTADOS DE MEJORA DE RUGOSIDAD, PRECISIÓN Y TOLERANCIA");
        jLabel7.setToolTipText("");

        jButtonAceptar.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jButtonAceptar.setText("Nuevo cálculo");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jButtonAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAceptarKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jLabel8.setText("Porcentaje de mejora de Rugosidad Estimada: (%)");

        jTextFieldPorcentajeRugosidad.setEditable(false);
        jTextFieldPorcentajeRugosidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPorcentajeRugosidadKeyPressed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jLabel9.setText("Porcentaje de mejora de Precisión estimada: (%)");

        jTextFieldPorcentajePrecision.setEditable(false);
        jTextFieldPorcentajePrecision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPorcentajePrecisionKeyPressed(evt);
            }
        });

        jLabelMecanizado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabelMecanizado.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMecanizado.setText("AAAAA");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jLabel1.setText("Tipo de material: ");

        jTextFieldTipoDeMaterial.setEditable(false);
        jTextFieldTipoDeMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTipoDeMaterialKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jLabel2.setText("Rugosidad final estimada: (µm)");

        jTextFieldRugosidadFinal.setEditable(false);
        jTextFieldRugosidadFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRugosidadFinalKeyPressed(evt);
            }
        });

        jLabelTolerancia.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        jLabelTolerancia.setText("Tolerancia final estimada: (µm)");

        jTextFieldTolerancia.setEditable(false);
        jTextFieldTolerancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldToleranciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMecanizado)
                .addGap(208, 208, 208))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabelTolerancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPorcentajePrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipoDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPorcentajeRugosidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRugosidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jButtonAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMecanizado)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTipoDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPorcentajeRugosidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPorcentajePrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRugosidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTolerancia)
                    .addComponent(jTextFieldTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        
        this.setVisible(false);

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DecimalFormat formato1 = new DecimalFormat("#.###");

        if (meca == 1) {
            jLabelMecanizado.setText("Fresado");
            switch (material) {
                
                case 1:
                    jTextFieldTipoDeMaterial.setText("ABS");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

                case 2:
                    jTextFieldTipoDeMaterial.setText("PC");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }

                    break;

                case 3:
                    jTextFieldTipoDeMaterial.setText("EPC-CF");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;
                    
                 default:
                    Util.mostrarError("Error en el form info");
                    break;

            }

        } else {
            jLabelMecanizado.setText("Taladrado");
            switch (material) {

                default:
                    Util.mostrarError("Error en el form info");
                    break;
                case 1:
                    jTextFieldTipoDeMaterial.setText("ABS");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

                case 2:
                    jTextFieldTipoDeMaterial.setText("PC");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }

                    break;

                case 3:
                    jTextFieldTipoDeMaterial.setText("EPC-CF");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

            }

        }
    }//GEN-LAST:event_formWindowOpened

    private void jButtonAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAceptarKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jButtonAceptarKeyPressed

    private void jTextFieldPorcentajeRugosidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPorcentajeRugosidadKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldPorcentajeRugosidadKeyPressed

    private void jTextFieldTipoDeMaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTipoDeMaterialKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldTipoDeMaterialKeyPressed

    private void jTextFieldPorcentajePrecisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPorcentajePrecisionKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldPorcentajePrecisionKeyPressed

    private void jTextFieldRugosidadFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRugosidadFinalKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldRugosidadFinalKeyPressed

    private void jTextFieldToleranciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldToleranciaKeyPressed
        if ((int) evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER) {
            jButtonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldToleranciaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       DecimalFormat formato1 = new DecimalFormat("#.###");

        if (meca == 1) {
            jLabelMecanizado.setText("Fresado");
            switch (material) {
                
                case 1:
                    jTextFieldTipoDeMaterial.setText("ABS");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

                case 2:
                    jTextFieldTipoDeMaterial.setText("PC");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }

                    break;

                case 3:
                    jTextFieldTipoDeMaterial.setText("EPC-CF");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;
                    
                 default:
                    Util.mostrarError("Error en el form info");
                    break;

            }

        } else {
            jLabelMecanizado.setText("Taladrado");
            switch (material) {

                default:
                    Util.mostrarError("Error en el form info");
                    break;
                case 1:
                    jTextFieldTipoDeMaterial.setText("ABS");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

                case 2:
                    jTextFieldTipoDeMaterial.setText("PC");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }

                    break;

                case 3:
                    jTextFieldTipoDeMaterial.setText("EPC-CF");
                    jTextFieldPorcentajeRugosidad.setText(
                            formato1.format(obj.mejoraDeRugosidad));
                    jTextFieldPorcentajePrecision.setText(
                            formato1.format(obj.mejoraDePrecision));
                    jTextFieldRugosidadFinal.setText(formato1.format(obj.rugosidadFinal));
                    if (obj.getTolerancia() != 0) {
                        FormInfo.this.jLabelTolerancia.setVisible(true);
                        FormInfo.this.jTextFieldTolerancia.setVisible(true);
                        jTextFieldTolerancia.setText(formato1.format(obj.toleranciaFinal));
                    }
                    break;

            }

        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMecanizado;
    private javax.swing.JLabel jLabelTolerancia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldPorcentajePrecision;
    private javax.swing.JTextField jTextFieldPorcentajeRugosidad;
    private javax.swing.JTextField jTextFieldRugosidadFinal;
    private javax.swing.JTextField jTextFieldTipoDeMaterial;
    private javax.swing.JTextField jTextFieldTolerancia;
    // End of variables declaration//GEN-END:variables
}
